config/routes.rb
Rails.application.routes.draw do
  get 'relatorio/filtro'

  get 'relatorio/gerar'
  post 'relatorio/gerar' => 'relatorio#gerar', :as => 'post_relatorio_gerar'  

  resources :servico_items
  resources :produto_items
  resources :ordem_servicos
  resources :funcionarios
  resources :emails
  resources :enderecos
  resources :telefones
  get 'dashboard/index'

  resources :servicos
  resources :produtos
  resources :clientes
  devise_for :users

  root 'dashboard#index'

  get 'search/ajax_search'
  get 'search/search_by_id'
  get 'search/ajax_search_externo'

  get 'ordem_servicos/:id/encerrar' => 'ordem_servicos#encerrar', :as => 'ordem_servico_encerrar'
  put 'ordem_servicos/:id/encerrar' => 'ordem_servicos#encerrar', :as => 'put_ordem_servico_encerrar'
  patch 'ordem_servicos/:id/encerrar' => 'ordem_servicos#encerrar'

  get 'ordem_servicos/:id/reabrir' => 'ordem_servicos#reabrir', :as => 'ordem_servico_reabrir'
  put 'ordem_servicos/:id/reabrir' => 'ordem_servicos#reabrir', :as => 'put_ordem_servico_reabrir'
  patch 'ordem_servicos/:id/reabrir' => 'ordem_servicos#reabrir'
end

app/models/produto.rb
class Produto < ApplicationRecord
  validates :descricao, presence: true
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @operacao = "Visualização"
  end

  # GET /produtos/new
  def new
    @operacao = "Inclusão"
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
    @operacao = "Edição"
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: t('messages.cadastro_salvo') }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: t('messages.cadastro_atualizado') }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: t('messages.cadastro_removido') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:descricao, :preco_compra, :preco_venda)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<br/>
<div class="row">
  <div class="col-lg-6">
    <%= link_to t('buttons.voltar'), produtos_path, :class=>"btn btn-sm btn-default" %>
  </div>
</div>
<br/>

<%= render_alerts @produto %>
<br>

<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
      <%= @operacao %>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_with(model: produto, local: true) do |form| %>          
              <div class="form-group">
                <%= form.label :descricao %>
                <%= form.text_field :descricao, id: :produto_descricao, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <%= form.label :preco_compra %>
                <%= form.text_field :preco_compra, id: :produto_preco_compra,:class=>"form-control currency" %>
              </div>

              <div class="form-group">
                <%= form.label :preco_venda %>
                <%= form.text_field :preco_venda, id: :produto_preco_venda, :class=>"form-control currency" %>
              </div>

              <div class="actions">
                <button type="submit" class="btn btn-sm btn-primary"><%= t('buttons.gravar') %></button>
              </div>
            <% end %>
          </div>
        </div>
        <!-- /.row (nested) -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
</div>

app/views/produtos/edit.html.erb
<%= render 'form', produto: @produto %>

app/views/produtos/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= Produto.model_name.human(count: @produtos.size) %></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
        <table class="table table-sm">
            <thead>
              <tr>
                <th>Descrição</th>
                <th>Preco de Compra</th>
                <th>Preco de Venda</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @produtos.each do |produto| %>
                <tr>
                  <td><%= produto.descricao %></td>
                  <td><%= get_valor_formatado produto.preco_compra %></td>
                  <td><%= get_valor_formatado produto.preco_venda %></td>
                  <td style="width: 3%; text-align: center;">
                    <%= link_to produto, class:"btn btn-primary btn-circle" do %>
                      <i class="fa fa-eye"></i>
                    <% end %>
                  </td>
                  <td style="width: 3%; text-align: center;">
                    <%= link_to edit_produto_path(produto), class:"btn btn-success btn-circle" do %>
                      <i class="fa fa-edit"></i>
                    <% end %>
                  </td>
                  <td style="width: 3%; text-align: center;">
                    <%= link_to produto, method: :delete, data: { confirm: t('messages.confirma_remocao') }, class:"btn btn-danger btn-circle" do %>
                      <i class="fa fa-times"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>

<br/>
<div class="row">
  <div class="col-lg-6">
    <%= link_to t('buttons.novo'), new_produto_path, :class=>"btn btn-sm btn-primary" %>
  </div>
</div>

app/views/produtos/new.html.erb
<%= render 'form', produto: @produto %>

app/views/produtos/show.html.erb
<br/>
<div class="row">
  <div class="col-lg-6">
    <%= link_to t('buttons.voltar'), produtos_path, :class=>"btn btn-sm btn-default" %>
    <%= link_to t('buttons.editar'), edit_produto_path(@produto.id), :class=>"btn btn-sm btn-primary" %>
  </div>
</div>
<br/>

<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
      <%= @operacao %>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_with(model: @produto, local: true) do |form| %>
            <div class="form-group">
              <%= form.label :descricao %>
              <%= form.text_field :descricao, id: :produto_descricao, :class=>"form-control show", :readonly=>"true" %>
            </div>

            <div class="form-group">
              <%= form.label :preco_compra %>
              <%= form.text_field :preco_compra, id: :produto_preco_compra, :class=>"form-control currency show", :readonly=>"true" %>
            </div>

            <div class="form-group">
              <%= form.label :preco_venda %>
              <%= form.text_field :preco_venda, id: :produto_preco_venda, :class=>"form-control currency show", :readonly=>"true" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>