config/routes.rb
Rails.application.routes.draw do
  get 'relatorio/filtro'

  get 'relatorio/gerar'
  post 'relatorio/gerar' => 'relatorio#gerar', :as => 'post_relatorio_gerar'  

  resources :servico_items
  resources :produto_items
  resources :ordem_servicos
  resources :funcionarios
  resources :emails
  resources :enderecos
  resources :telefones
  get 'dashboard/index'

  resources :servicos
  resources :produtos
  resources :clientes
  devise_for :users

  root 'dashboard#index'

  get 'search/ajax_search'
  get 'search/search_by_id'
  get 'search/ajax_search_externo'

  get 'ordem_servicos/:id/encerrar' => 'ordem_servicos#encerrar', :as => 'ordem_servico_encerrar'
  put 'ordem_servicos/:id/encerrar' => 'ordem_servicos#encerrar', :as => 'put_ordem_servico_encerrar'
  patch 'ordem_servicos/:id/encerrar' => 'ordem_servicos#encerrar'

  get 'ordem_servicos/:id/reabrir' => 'ordem_servicos#reabrir', :as => 'ordem_servico_reabrir'
  put 'ordem_servicos/:id/reabrir' => 'ordem_servicos#reabrir', :as => 'put_ordem_servico_reabrir'
  patch 'ordem_servicos/:id/reabrir' => 'ordem_servicos#reabrir'
end

app/models/ordem_servico.rb
class OrdemServico < ApplicationRecord
  has_many :servico_items, dependent: :destroy
  has_many :produto_items, dependent: :destroy
  belongs_to :cliente
  belongs_to :funcionario
  accepts_nested_attributes_for :servico_items, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :produto_items, reject_if: :all_blank, allow_destroy: true

  before_create :valida_data_previsao
  before_update :valida_data_previsao

  validates :cliente_id, presence: true
  validates :data_previsao, presence: true
  validates_presence_of :servico_items

  def encerrada?
    self.data_encerramento.present?
  end

  def aberta?
    !self.data_encerramento.present?
  end

  def get_status
    self.encerrada? ? "Encerrada" : "Aberta"
  end

  def get_valor_ordem_servico
    valor = 0
    return valor unless self.present?

    if self.produto_items.present?
      self.produto_items.each do |prod|
        valor += prod.quantidade * prod.preco_unitario if prod.quantidade.present?
      end
    end

    if self.servico_items.present?
      self.servico_items.each do |s|
        valor += s.quantidade_horas * s.preco_hora if s.quantidade_horas.present?
      end
    end
  end

  def valida_data_previsao
    return self.data_previsao if self.data_previsao.nil?

    if self.data_previsao.to_date <= Date.today
      self.errors[:data_previsao] << "deve ser maior que data atual"
    end
  end
end

app/controllers/ordem_servicos_controller.rb
class OrdemServicosController < ApplicationController
  before_action :set_ordem_servico, only: [:show, :edit, :update, :destroy, :encerrar, :reabrir]
  #after_action :atualiza_valor_total, only: [:create, :update]
  before_action :authenticate_user!

  # GET /ordem_servicos
  # GET /ordem_servicos.json
  def index
    @ordem_servicos = OrdemServico.all
  end

  # GET /ordem_servicos/1
  # GET /ordem_servicos/1.json
  def show
    @operacao = 'Visualização'
  end

  # GET /ordem_servicos/new
  def new
    @operacao = 'Inclusão'
    @ordem_servico = OrdemServico.new
    @ordem_servico.servico_items.build
    @ordem_servico.produto_items.build
  end

  # GET /ordem_servicos/1/edit
  def edit
    @operacao = 'Edição'
  end

  def encerrar
    if @ordem_servico.encerrada?
      render :show, notice: 'A ordem de serviço já está encerrada'
      return
    end

    @ordem_servico.data_encerramento = Date.today
    @ordem_servico.save
    redirect_to @ordem_servico, notice: 'Ordem de serviço encerrada com  sucesso.' and return
  end

  def reabrir
    if @ordem_servico.aberta?
      render :show, notice: 'A ordem de serviço já está aberta'
      return
    end

    @ordem_servico.data_encerramento = ''
    @ordem_servico.save
    redirect_to @ordem_servico, notice: 'Ordem de servico reaberta com sucesso.' and return

  end

  # POST /ordem_servicos
  # POST /ordem_servicos.json
  def create
    @ordem_servico = OrdemServico.new(ordem_servico_params)
    set_funcionario
    @ordem_servico.valor_total = @ordem_servico.get_valor_ordem_servico

    respond_to do |format|
      if @ordem_servico.save
        format.html { redirect_to @ordem_servico, notice: t('messages.cadastro_salvo')}
        format.json { render :show, status: :created, location: @ordem_servico }
      else
        @ordem_servico.servico_items.build unless @ordem_servico.servico_items.size > 0
        @ordem_servico.produto_items.build unless @ordem_servico.produto_items.size > 0
        format.html { render :new }
        format.json { render json: @ordem_servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordem_servicos/1
  # PATCH/PUT /ordem_servicos/1.json
  def update
    respond_to do |format|
      set_funcionario
      if @ordem_servico.update(ordem_servico_params)
        format.html { redirect_to @ordem_servico, notice: t('messages.cadastro_atualizado') }
        format.json { render :show, status: :ok, location: @ordem_servico }
      else
        format.html { render :edit }
        format.json { render json: @ordem_servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordem_servicos/1
  # DELETE /ordem_servicos/1.json
  def destroy
    @ordem_servico.destroy
    respond_to do |format|
      format.html { redirect_to ordem_servicos_url, notice: t('messages.cadastro_removido') }
      format.json { head :no_content }
    end
  end

  def atualiza_valor_total
    @ordem_servico.valor_total = @ordem_servico.get_valor_ordem_servico
    @ordem_servico.save!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordem_servico
      @ordem_servico = OrdemServico.find(params[:id])
    end

    def set_funcionario
      @funcionario = Funcionario.find_by(user_id: authenticate_user!.id)
      @ordem_servico.funcionario_id = @funcionario.id if @funcionario.present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordem_servico_params
      params.require(:ordem_servico).permit(
        :cliente_id,
        :problema,
        :equipamento,
        :funcionario_id,
        :data_encerramento,
        :data_previsao,
        :valor_total,
        produto_items_attributes: [:id, :produto_id, :quantidade, :preco_unitario, :valor_total, :_destroy],
        servico_items_attributes: [:id, :servico_id, :quantidade_horas, :preco_hora, :valor_total, :_destroy]
      )
    end
end

app/helpers/ordem_servicos_helper.rb
module OrdemServicosHelper
end

app/views/ordem_servicos/_produto_item_fields.html.erb
<div class="nested-fields">
  <div class="form-group field">
    <div class="row">
      <div class="col-md-5">
        <%= f.label :produto_id %>
      </div>
      <div class="col-md-2">
        <%= f.label :quantidade %>
      </div>
      <div class="col-md-2">
        <%= f.label :preco_unitario %>
      </div>
      <div class="col-md-2">
        <%= f.label :valor_total %>
      </div>

      <div class="col-md-5">
        <%= f.text_field :produto_id, :class=>"form-control produto_id" %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :quantidade, :class=>"form-control quantidade currency" %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :preco_unitario, :class=>"form-control preco_unitario currency" %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :valor_total, :class=>"form-control valor_total_produto currency show", :readonly=>'readonly' %>
      </div>

      <div class="col-md-1">
        <%= link_to_remove_association('', f, class: "btn btn-sm btn-warning fa fa-times btn-remover")%>
      </div>
    </div>
  </div>
</div>

<script>
  // BUSCAS VIA AJAX
  function prepara_campos() {
    BuscaProduto( $('.produto_id'), {});
  }

  prepara_campos();
</script>

app/views/ordem_servicos/_servico_item_fields.html.erb
<div class="nested-fields">
  <div class="form-group field">
    <div class="row">
      <div class="col-md-5">
        <%= f.label :servico_id %>
      </div>
      <div class="col-md-2">
        <%= f.label :quantidade_horas %>
      </div>
      <div class="col-md-2">
        <%= f.label :preco_hora %>
      </div>
      <div class="col-md-2">
        <%= f.label :valor_total %>
      </div>

      <div class="col-md-5">
        <%= f.text_field :servico_id, :class=>"form-control servico_id" %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :quantidade_horas, :class=>"form-control quantidade_horas currency" %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :preco_hora, :class=>"form-control preco_hora currency" %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :valor_total, :class=>"form-control valor_total_servico currency show", :readonly=>'readonly' %>
      </div>

      <div class="col-md-1">
        <%= link_to_remove_association('', f, class: "btn btn-sm btn-warning fa fa-times btn-remover")%>
      </div>
    </div>
  </div>
</div>

<script>
  // BUSCAS VIA AJAX
  function prepara_campos() {
    BuscaServico( $('.servico_id'), {});
  }

  prepara_campos();
</script>

app/views/ordem_servicos/edit.html.erb
<%= render 'form', ordem_servico: @ordem_servico %>

app/views/ordem_servicos/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= OrdemServico.model_name.human(count: @ordem_servicos.size) %></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
        <table class="table table-sm">
          <thead>
            <tr>
              <th>Cliente</th>
              <th>CPF/CNPJ</th>
              <th>Funcionário</th>
              <th>Data de Abertura</th>
              <th>Previsão</th>
              <th>Status</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @ordem_servicos.each do |ordem_servico| %>
              <tr>
                <td><%= ordem_servico.cliente.nome %></td>
                <td><%= ordem_servico.cliente.cpf_cnpj %></td>
                <td><%= ordem_servico.funcionario.nome %></td>
                <td><%= datef(ordem_servico.created_at) %></td>
                <td><%= ordem_servico.data_previsao %></td>
                <td>
                  <% if ordem_servico.get_status == 'Encerrada' %>
                    <span class="label label-success">
                      <%= ordem_servico.get_status %>
                    </span>
                  <% else %>
                    <span class="label label-warning">
                      <%= ordem_servico.get_status %>
                    </span>
                  <% end %>
                </td>
                <td style="width: 3%; text-align: center;">
                  <%= link_to ordem_servico, class:"btn btn-primary btn-circle" do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                </td>
                <td style="width: 3%; text-align: center;">
                  <%= link_to edit_ordem_servico_path(ordem_servico), class:"btn btn-success btn-circle" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                </td>
                <td style="width: 3%; text-align: center;">
                  <%= link_to ordem_servico, method: :delete, data: { confirm: t('messages.confirma_remocao') }, class:"btn btn-danger btn-circle" do %>
                    <i class="fa fa-times"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

<br/>
<div class="row">
  <div class="col-lg-6">
    <%= link_to t('buttons.novo'), new_ordem_servico_path, :class=>"btn btn-sm btn-primary" %>
  </div>
</div>

app/views/ordem_servicos/new.html.erb
<%= render 'form', ordem_servico: @ordem_servico %>

app/views/ordem_servicos/show.html.erb
<br/>
<div class="row">
  <div class="col-lg-6">
    <%= link_to t('buttons.voltar'), ordem_servicos_path, :class=>"btn btn-sm btn-default" %>
    <% if @ordem_servico.aberta? %>
      <%= link_to t('buttons.editar'), edit_ordem_servico_path(@ordem_servico.id), :class=>"btn btn-sm btn-primary" %>
      <%= link_to t('buttons.encerrar'), put_ordem_servico_encerrar_path(@ordem_servico.id), :class=>"btn btn-sm btn-success" %>
    <% else %>
      <%= link_to t('buttons.reabrir'), put_ordem_servico_reabrir_path(@ordem_servico.id), :class=>"btn btn-sm btn-warning" %>
    <% end %>

  </div>
</div>
<br/>

<%= form_with(model: @ordem_servico, local: true) do |form| %>

  <div class="row">
    <div class="col-md-12 col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
        Visualização - Info. Principais
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-8">
              <div class="form-group">
                <%= form.label :cliente, :class=>"control-label" %>
                <input id="cliente_nome" class="form-control show" readonly="readonly" type="text" value="<%= @ordem_servico.cliente.nome %>" name="cliente[nome]">
              </div>
            </div>
            <div class="col-lg-4">
              <div class="form-group">
                <%= form.label :data_previsao %>
                <%= form.text_field :data_previsao, id: :ordem_servico_data_previsao, value: @ordem_servico.data_previsao, :class=>"form-control show", :readonly=>"true"%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
        Info. Adicionais
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-12">
              <div class="form-group">
                <%= form.label :equipamento %>
                <%= form.text_field :equipamento, id: :ordem_servico_equipamento, :class=>"form-control show", :readonly=>"true"  %>
              </div>
              <div class="form-group">
                <%= form.label :problema %>
                <%= form.text_area :problema, id: :ordem_servico_problema, :class=>"form-control problema_os show", :readonly=>"true"  %>
              </div>
            </div>
          </div>
          </div>
          <!-- /.row (nested) -->
        <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>

  </div>

  <div class="row">
    <div class="col-md-12 col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
        Produtos
        </div>

        <div class="panel-body">
          <div class="row">
            <div id="produto_items" class="col-lg-12">
              <%= form.fields_for :produto_items do |t| %>
                <div class="row">
                  <div class="col-md-6">
                    <%= t.label :produto_id %>
                  </div>
                  <div class="col-md-2">
                    <%= t.label :quantidade %>
                  </div>
                  <div class="col-md-2">
                    <%= t.label :preco_unitario %>
                  </div>
                  <div class="col-md-2">
                    <%= t.label :valor_total %>
                  </div>

                  <div class="col-md-6">
                    <%= t.text_field :produto_id, :class=>"form-control produto_id", :readonly=>"true" %>
                  </div>
                  <div class="col-md-2">
                    <%= t.text_field :quantidade, :class=>"form-control quantidade currency show", :readonly=>"true" %>
                  </div>
                  <div class="col-md-2">
                    <%= t.text_field :preco_unitario, :class=>"form-control preco_unitario currency show", :readonly=>"true" %>
                  </div>
                  <div class="col-md-2">
                    <%= t.text_field :valor_total, :class=>"form-control valor_total_produto currency show", :readonly=>'readonly' %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
        Servicos
        </div>

        <div class="panel-body">
          <div class="row">
            <div id="servico_items" class="col-lg-12">
              <%= form.fields_for :servico_items do |t| %>
                <div class="row">
                  <div class="col-md-6">
                    <%= t.label :servico_id %>
                  </div>
                  <div class="col-md-2">
                    <%= t.label :quantidade_horas %>
                  </div>
                  <div class="col-md-2">
                    <%= t.label :preco_hora %>
                  </div>
                  <div class="col-md-2">
                    <%= t.label :valor_total %>
                  </div>

                  <div class="col-md-6">
                    <%= t.text_field :servico_id, :class=>"form-control servico_id", :readonly=>"true" %>
                  </div>
                  <div class="col-md-2">
                    <%= t.text_field :quantidade_horas, :class=>"form-control quantidade_horas currency show", :readonly=>"true" %>
                  </div>
                  <div class="col-md-2">
                    <%= t.text_field :preco_hora, :class=>"form-control preco_hora currency show", :readonly=>"true" %>
                  </div>
                  <div class="col-md-2">
                    <%= t.text_field :valor_total, :class=>"form-control valor_total_produto currency show", :readonly=>'readonly' %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row" style="float: right;">
    <div class="col-lg-12">
      <div class="form-group">
        <%= form.label :valor_total, :class=>"control-label" %>
        <%= form.text_field :valor_total, id: :ordem_servico_valor_total, :class=>"form-control currency show", :readonly=>'readonly'%>
      </div>

    </div>
  </div>

  <br>
  <br>
  <br>
  <br><br>

<script>
  // BUSCAS VIA AJAX

  function carrega_preco(tipo, nome, id){
    var qtd_caracteres = nome.lastIndexOf('][') - nome.lastIndexOf('s][') - 3;
    var indice = nome.substr(40,qtd_caracteres);
    var campo_preco = '#ordem_servico_'.concat(tipo).concat('_items_attributes_').concat(indice)
    if (tipo == 'produto'){
        campo_preco = campo_preco.concat('_preco_unitario');
        $.ajax({
          type: "GET",
          url: "/search/search_by_id",
          data: { id: $('#'.concat(id)).val(), model: "Produto" },
          success: function(data){
            $(campo_preco).val(data.preco_venda);
          },
          dataType: "json"
        });
    } else {
        campo_preco = campo_preco.concat('_preco_hora');
        $.ajax({
          type: "GET",
          url: "/search/search_by_id",
          data: { id: $('#'.concat(id)).val(), model: "Servico" },
          success: function(data){
            $(campo_preco).val(data.preco_hora);
          },
          dataType: "json"
        });
    }
  }

  function recalcula_total_produto(nome) {
    var qtd_caracteres = nome.lastIndexOf('][') - nome.lastIndexOf('s][') - 3;
    var indice = nome.substr(40,qtd_caracteres);
    var campo_qtd = '#ordem_servico_produto_items_attributes_'.concat(indice).concat('_quantidade');
    var campo_preco = '#ordem_servico_produto_items_attributes_'.concat(indice).concat('_preco_unitario');
    var valor_total = '#ordem_servico_produto_items_attributes_'.concat(indice).concat('_valor_total');
    var qtd = $(campo_qtd).val().replace('.', '').replace(',', '.')
    var preco = $(campo_preco).val().replace('.', '').replace(',', '.')
    $(valor_total).val(qtd*preco);
    recalcula_total();
  }

  function recalcula_total_servico(nome) {
    var qtd_caracteres = nome.lastIndexOf('][') - nome.lastIndexOf('s][') - 3;
    var indice = nome.substr(40,qtd_caracteres);
    var campo_qtd = '#ordem_servico_servico_items_attributes_'.concat(indice).concat('_quantidade_horas');
    var campo_preco = '#ordem_servico_servico_items_attributes_'.concat(indice).concat('_preco_hora');
    var valor_total = '#ordem_servico_servico_items_attributes_'.concat(indice).concat('_valor_total');
    var qtd = $(campo_qtd).val().replace('.', '').replace(',', '.')
    var preco = $(campo_preco).val().replace('.', '').replace(',', '.')
    $(valor_total).val(qtd*preco);
    recalcula_total();
  }

  function adiciona_mascaras(){
    Mask(".currency");
    $('#produto_items').off("change.quantidade");
    $('#servico_items').off("change.quantidade");

    $('#produto_items').on("change .quantidade", function(e) {
      recalcula_total_produto(e.target.name);
    });

    $('#servico_items').on("change .quantidade_horas", function(e) {
      recalcula_total_servico(e.target.name);
    });

    $('#produto_items').on("change .produto_id", function(e) {
      carrega_preco('produto', e.target.name, e.target.id);
    });

    $('#servico_items').on("change .servico_id", function(e) {
      carrega_preco('servico', e.target.name, e.target.id);
    });
  }

  function recalcula_total() {
    var valor;
    var valor_servico;
    var aux;

    valor = 0;
    valor_servico = 0;

    $('.valor_total_produto').each(function(index, element) {
      aux = parseFloat($(element).val().replace('.', '').replace(',', '.'));
      if (!isNaN(aux)){
        valor += aux;
      }

    });

    $('.valor_total_servico').each(function(index, element) {
      aux = parseFloat($(element).val().replace('.', '').replace(',', '.'));
      if (!isNaN(aux)){
        valor_servico += aux;
      }
    });

    $('#ordem_servico_valor_total').val(valor + valor_servico);
  }

  $('#produto_items').on("change .quantidade", function(e) {
    recalcula_total_produto(e.target.name);
  });

  $('#servico_items').on("change .quantidade_horas", function(e) {
    recalcula_total_servico(e.target.name);
  });

  $('#produto_items').on("click .btn-remover", function(e) {
    recalcula_total();
  });

  $('#servico_items').on("click .btn-remover", function(e) {
    recalcula_total();
  });

  $("#produto_items").on("click", ".btn-adicionar", function(e) {
    setTimeout(adiciona_mascaras, 300);
  });

  $("#servico_items").on("click", ".btn-adicionar", function(e) {
    setTimeout(adiciona_mascaras, 300);
  });

  $('#produto_items').on("change .produto_id", function(e) {
    carrega_preco('produto', e.target.name, e.target.id);
  });

  $('#servico_items').on("change .servico_id", function(e) {
    carrega_preco('servico', e.target.name, e.target.id);
  });

  function prepara_campos() {
    BuscaProduto( $('.produto_id'), {});
    BuscaServico( $('.servico_id'), {});
  }

  prepara_campos();

</script>
<% end %>